[package]
name = "updater"
version = "1.0.0"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
reqwest = { version = "0.12", features = ["blocking", "json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
zip = "0.6"