name: vice
description: "A Virtual Mic Util App"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  
  js: ^0.6.7
  flutter_colorpicker: ^1.1.0
  font_awesome_flutter: ^10.7.0
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
