name: vice
description: "A Virtual Mic Util App"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  js: ^0.6.7
  flutter_lints: ^5.0.0
  flutter_colorpicker: ^1.1.0

flutter:
  uses-material-design: true
